davidhazagury/discomfortzone

- app/models/event.rb
- app/models/event_user.rb
- app/models/favourite.rb
- app/models/goal.rb
- app/models/message.rb
- app/models/review.rb
- app/models/user.rb
- config/puma.rb
- db/migrate/20200622143822_create_goals.rb
- db/migrate/20200622144301_create_events.rb
- db/migrate/20200622145148_create_reviews.rb
- db/migrate/20200622150949_create_messages.rb
- db/migrate/20200622151010_create_favourites.rb
- db/migrate/20200622151120_create_event_users.rb
- db/schema.rb
- test/models/event_test.rb
- test/models/event_user_test.rb
- test/models/favourite_test.rb
- test/models/goal_test.rb
- test/models/message_test.rb
- test/models/review_test.rb
> All models creation done

- app/models/event.rb
Forgot to save the file, before pushing the old pull request
> Event file mistake

- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Add funny under construction image
> Under construction

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Added cloudinary gem. Forgot when setting it up.
> Forgot to add the cloudinary gem. Now FIXED

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/events_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/javascript/plugins/init_mapbox.js
- app/models/event.rb
- app/models/user.rb
- app/views/events/_info_window.html.erb
- app/views/events/show.html.erb
- config/initializers/geocoder.rb
- db/migrate/20200622174005_add_coordinates_to_event.rb
- db/schema.rb
- package.json
- test/controllers/events_controller_test.rb
- yarn.lock
Finished the map with markers and also autocomplete for the form.
Didn't get to test it yet because we don't have yet a show page, nor a view. 
Hopefully should be all good! Nothing that can't be fixed anyway.
> Map feature, markers, and address autocomplete are DONE

- config/routes.rb
Created the routes for the events.
> Routes for events

- app/controllers/events_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/events/show.html.erb
- config/routes.rb
- db/migrate/20200623094641_add_name_to_users.rb
- db/schema.rb
Show method created, same fort the view. Pundit will break the code, but need to authorize it
> Show method created

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/events_controller.rb
- app/controllers/pages_controller.rb
- app/models/event.rb
- app/policies/application_policy.rb
- app/policies/event_policy.rb
- test/policies/event_policy_test.rb
Implemented pundit, let's take a loot at it together on the table:)
> Advancements in the pundit setup

- app/policies/event_policy.rb
- app/views/devise/registrations/new.html.erb
Made some changes on the SIGN-UP FORM. Added inputs for first_name and last_name
> Added first name and last name on the sign up form

- app/controllers/events_controller.rb
- app/policies/event_policy.rb
- app/views/events/new.html.erb
- db/migrate/20200623131618_create_active_storage_tables.active_storage.rb
- db/schema.rb
Made the new & create method, the simple form (including the upload for the picture).
Pundit it´s included and running
> Creation of a new event by the current user.

- app/controllers/events_controller.rb
- app/models/event.rb
- app/models/event_user.rb
- app/views/events/index.html.erb
- db/migrate/20200623135709_change_event_user_status.rb
- db/schema.rb
- db/seeds.rb
created status table migration for event_users, + 3 different states (accepted, rejected, applied), + spots_left method inside of event model
> Seeds and adding migration

- app/controllers/events_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/events/index.html.erb
- db/schema.rb
- db/seeds.rb
> Personalized avatar

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/events/_index.scss
- app/views/events/index.html.erb
- db/seeds.rb
> css cards & events index

- app/assets/stylesheets/components/_mobile_navbar.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/shared/_mobile_navbar.html.erb
Some tiny fixes:
Dowloaded and Changed the base fonts (Monsterrat and Lato)
Made all the icons for the mobile navbar
Added our main website colors (we'll mostly be using $main-blue i guess)
Fixed the padding and sizing of the mobile navbar
> Small navbar adjustments

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/events/_index.scss
- app/views/events/index.html.erb
Cleaned up the (view) index of events and the _card.scss, to have a better base to create the final cards
> cleaned up index and card.scss

- app/controllers/event_users_controller.rb
- app/models/event.rb
- app/models/user.rb
- app/policies/event_user_policy.rb
- app/views/event_users/index.html.erb
Done it together with Wolfgang and Rui
> Fixed the database to make the dashboard work

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_letters_n_text.scss
- app/assets/stylesheets/components/_mobile_navbar_bottom.scss
- app/assets/stylesheets/components/_mobile_navbar_top.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/pages/home.html.erb
- app/views/shared/_mobile_navbar_bottom.html.erb
- app/views/shared/_mobile_navbar_top.html.erb
* Added buttons to the bottom navbar
* Did some styling on the home page (images, color contrast, font sizes & weights)
* Changed the logo and Flipped the Z!!!
> Home page styling

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/events/index.html.erb
Also added a new color : $blue-gray
> Fixed front end for the index cards

- app/assets/stylesheets/components/_navbar_desktop.scss
- app/channels/event_channel.rb
- app/controllers/chats_controller.rb
- app/controllers/events_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/channels/event_channel.js
- app/models/event.rb
- app/policies/chat_policy.rb
- app/policies/message_policy.rb
- app/views/chats/show.html.erb
- app/views/events/show.html.erb
- app/views/messages/_message.html.erb
- config/cable.yml
- config/routes.rb
- db/seeds.rb
- test/channels/event_channel_test.rb
- test/controllers/chats_controller_test.rb
- test/controllers/messages_controller_test.rb
Web socket
Action Cable
Chat feature working + displaying different things based on if the user is a host and/or accepted
> Messages feature implementation

- app/controllers/event_users_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_flatpickr.js
- app/views/event_users/index.html.erb
> dashboard2

- app/controllers/chats_controller.rb
- app/controllers/events_controller.rb
- app/policies/chat_policy.rb
quick SQL update on the index search to also include address
Refactored the chat backend to make it less complicated
> Thursday night fixes

- app/assets/stylesheets/pages/users/_show.scss
- app/views/users/show.html.erb
Working on the scroll-x feature for the list of event in the profile page
> Unfinished scroll on profile page

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/users/_show.scss
- app/views/users/show.html.erb
General front end of the profile page it´s done.
Still have to work on the scrolling cards and the edit button, so that it shows if the user is the owner of the profile
> Show page design finished

- app/assets/stylesheets/pages/event_users/_index.scss
- app/controllers/event_users_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/event_users/index.html.erb
- config/routes.rb
solved the "unsolvable" bug & implemented logic for favorites
> finished up dashboard

- app/assets/stylesheets/components/_card.scss
- app/channels/event_channel.rb
- app/controllers/messages_controller.rb
- app/javascript/channels/event_channel.js
- app/javascript/packs/application.js
- app/views/chats/show.html.erb
- app/views/events/show.html.erb
- config/routes.rb
Fixed the chat feature + some very minor adjustments
> Friday morning fixes

- app/views/events/show.html.erb
- db/seeds.rb
Made some nice seeds:)
- We need to fix ASAP the bottom margin issue we have
> New cool seeds

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/event_users/_index.scss
- app/views/event_users/index.html.erb
> dashboard front end

- app/channels/chat_channel.rb
> filename change for channel

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_letters_n_text.scss
- app/assets/stylesheets/components/_mobile_navbar_top.scss
- app/views/devise/sessions/new.html.erb
- app/views/events/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_mobile_navbar_top.html.erb
> Saturday fixes

- app/assets/stylesheets/components/_mobile_navbar_bottom.scss
- app/assets/stylesheets/components/_mobile_navbar_top.scss
- app/views/event_users/_new.html.erb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- app/views/shared/_mobile_navbar_bottom.html.erb
- app/views/shared/_mobile_navbar_top.html.erb
Fixed some CSS on the navbars, updated the links, reduced the amount of buttons in bottom navbar.
Also added some extra logic in the show & index cards so it shows 4/5 spots left, for example.
> Sunday css fixes

- app/assets/stylesheets/config/_colors.scss
- app/controllers/event_users_controller.rb
- app/controllers/events_controller.rb
- app/controllers/favourites_controller.rb
- app/controllers/goals_controller.rb
- app/policies/event_policy.rb
- app/policies/goal_policy.rb
- app/views/event_users/_new.html.erb
- app/views/goals/_new.html.erb
- db/migrate/20200628133742_add_completed_to_goals.rb
- db/migrate/20200628135551_add_biography_to_users.rb
- db/schema.rb
- test/controllers/goals_controller_test.rb
* Advanced quite a bit in the goals (bucket list) backend. Created the controller, added a "completed" column, created the pundit policy rules, and added the basic controller rules (still needs a bit of work).
> Sunday afternoon work

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/users/_index.scss
- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- app/views/event_users/index.html.erb
- app/views/users/index.html.erb
> first version of users index + search bar

- app/assets/stylesheets/components/_card.scss
- app/controllers/events_controller.rb
- app/views/events/index.html.erb
Most of the stuff on this branch was actually copied over to Wolfgang's users/index
> Index with users

- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/pages/users/_show.scss
- app/views/users/show.html.erb
General design implemented, still have to work on the fonts and there is one issue that needs a ticket
> User redesign

- app/views/events/index.html.erb
- app/views/shared/_mobile_navbar_top.html.erb
Quick fix on the navbar - should be all good now
> Fixed top navbar issue

- app/assets/stylesheets/components/_container.scss
- app/views/users/show.html.erb
Still missing the font styling, have to talk with Cecile about that al together.
> Fixed the background problem, plus added alignment. Missing font styling

- app/assets/stylesheets/components/_letters_n_text.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/event_users/_index.scss
- app/views/event_users/index.html.erb
- app/views/pages/home.html.erb
- app/views/users/show.html.erb
> Tuesday morning frontend sprint

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/events/index.html.erb
- app/views/shared/_card.html.erb
> Created Partial for the reworked card

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/pages/events/_show.scss
- app/views/events/show.html.erb
> New design implement. Missing fonts

- app/assets/stylesheets/components/_letters_n_text.scss
- app/assets/stylesheets/pages/users/_show.scss
- app/views/users/show.html.erb
> Reviews card reworked

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_letters_n_text.scss
- app/assets/stylesheets/components/_mobile_navbar_top.scss
- app/controllers/goals_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/home_navbar.js
- app/views/pages/home.html.erb
- app/views/shared/_mobile_navbar_top.html.erb
- app/views/users/show.html.erb
Home Page is basically done, just need to add some of Jonas's Cards.
> Home redesign

- app/views/event_users/update.js.erb
> fixed js bug

- app/assets/stylesheets/pages/event_users/_index.scss
- app/controllers/event_users_controller.rb
- app/models/event_user.rb
- app/views/event_users/_card.html.erb
- app/views/event_users/_new.html.erb
- app/views/event_users/index.html.erb
worked on the dashboard and changed styling quite a bit, partly with Cecile
> dashboard clean up

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_goal_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_letters_n_text.scss
- app/assets/stylesheets/components/_message.scss
- app/assets/stylesheets/components/_mobile_navbar_top.scss
- app/assets/stylesheets/pages/chats/_show.scss
- app/assets/stylesheets/pages/events/_new.scss
- app/javascript/packs/application.js
- app/javascript/plugins/home_navbar.js
- app/javascript/plugins/init_flatpickr.js
- app/views/chats/show.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/event_users/_new.html.erb
- app/views/events/new.html.erb
- app/views/goals/new.html.erb
- app/views/users/show.html.erb
CSS for forms, goals, home, and very beginning of chat. Fixed some goals back end as well.
> Form css styling

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_message.scss
- app/assets/stylesheets/components/_mobile_navbar_bottom.scss
- app/assets/stylesheets/components/_mobile_navbar_top.scss
- app/assets/stylesheets/pages/events/_show.scss
- app/assets/stylesheets/pages/users/_show.scss
- app/views/chats/show.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/event_users/_new.html.erb
- app/views/events/show.html.erb
- app/views/messages/_message.html.erb
- app/views/users/show.html.erb
> Tuesday night touchups

- app/assets/stylesheets/pages/event_users/_index.scss
- app/assets/stylesheets/pages/users/_index.scss
- app/views/users/index.html.erb
fixed the avatars on the card to be always centered, user index
> fixed user index

- app/assets/stylesheets/components/_message.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/chats/show.html.erb
- app/views/events/show.html.erb
- app/views/messages/_message.html.erb
- db/seeds.rb
Seeds, CSS, new Chat, Fixed show page logic
> Wednesday plane code

- app/assets/stylesheets/pages/event_users/_index.scss
> btn with they boyz

- app/assets/stylesheets/components/_mobile_navbar_top.scss
- app/views/shared/_mobile_navbar_top.html.erb
> added sign up button on top navbar

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_message.scss
- app/assets/stylesheets/pages/event_users/_index.scss
- app/assets/stylesheets/pages/events/_show.scss
- app/controllers/pages_controller.rb
- app/views/chats/show.html.erb
- app/views/event_users/_card.html.erb
- app/views/event_users/index.html.erb
- app/views/shared/_cards.html.erb
> Small CSS fixes left and right with Cecil

- app/policies/event_policy.rb
- db/seeds.rb
> index no longer shows old events

- app/assets/stylesheets/pages/events/_index.scss
- app/views/events/index.html.erb
- db/seeds.rb
> seeding my pic, decreasing margin of index search

- app/assets/stylesheets/pages/users/_index.scss
- db/seeds.rb
added seeds and fixed position of avatar with no picture in users index
> added seeds and fixed position of avatar with no picture in users index

- app/views/users/index.html.erb
- db/seeds.rb
seeds of my bio and background pic user index
> seeds of my bio and background pic user index

- app/controllers/event_users_controller.rb
Added a flash notification, when a user successfully applied to an event
> added a flash for when user applies for an event
